# Generated by Django 5.0.14 on 2026-09-21 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_contentblock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='record',
            name='show_in_gallery',
            field=models.BooleanField(default=True, help_text='Show this image in the About page gallery. Untick for logos and backgrounds.'),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(help_text='Main paragraph. Type [media:ID] to place a media-library image inside the text.')),
                ('bullets', models.TextField(blank=True, help_text='One capability per line.')),
                ('stats', models.TextField(blank=True, help_text='One per line as "Value | Label", e.g.  Java & .NET Core | Ecosystem Focus')),
                ('comparison', models.TextField(blank=True, help_text='Comparison table. First line = column headings, then one row per line. Separate columns with " | ".')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('media', models.ForeignKey(blank=True, help_text='Optional image from the media library.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='dashboard.record')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
